"""Update Spell Fields

Revision ID: ab1afeba8687
Revises: de51a9193a86
Create Date: 2026-02-01 22:30:37.570954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1afeba8687'
down_revision: Union[str, Sequence[str], None] = 'de51a9193a86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'forms', ['id'])
    op.add_column('powers', sa.Column('level', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'powers', ['id'])
    op.drop_column('powers', 'algonquian_title')
    op.create_unique_constraint(None, 'shapes', ['id'])
    op.create_unique_constraint(None, 'spells', ['id'])
    op.create_unique_constraint(None, 'sub_techniques', ['id'])
    op.add_column('targets', sa.Column('name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'targets', ['id'])
    op.drop_column('targets', 'type')
    op.create_unique_constraint(None, 'techniques', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'techniques', type_='unique')
    op.add_column('targets', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'targets', type_='unique')
    op.drop_column('targets', 'name')
    op.drop_constraint(None, 'sub_techniques', type_='unique')
    op.drop_constraint(None, 'spells', type_='unique')
    op.drop_constraint(None, 'shapes', type_='unique')
    op.add_column('powers', sa.Column('algonquian_title', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'powers', type_='unique')
    op.drop_column('powers', 'level')
    op.drop_constraint(None, 'forms', type_='unique')
    # ### end Alembic commands ###
