"""Make spell name unique

Revision ID: c553f5e5532c
Revises: 8e6d6148f835
Create Date: 2026-02-04 13:02:25.249906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c553f5e5532c'
down_revision: Union[str, Sequence[str], None] = '8e6d6148f835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'powers', ['tier'])
    op.create_unique_constraint(None, 'spells', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spells', type_='unique')
    op.drop_constraint(None, 'powers', type_='unique')
    # ### end Alembic commands ###
