"""Initial setup of spell tables

Revision ID: de51a9193a86
Revises: 
Create Date: 2026-02-01 20:01:00.540115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de51a9193a86'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('spell_school', sa.String(), nullable=False),
    sa.Column('latin_title', sa.String(), nullable=True),
    sa.Column('sanskrit_title', sa.String(), nullable=True),
    sa.Column('gaelic_title', sa.String(), nullable=True),
    sa.Column('polynesian_title', sa.String(), nullable=True),
    sa.Column('benoue_title', sa.String(), nullable=True),
    sa.Column('algonquian_title', sa.String(), nullable=True),
    sa.Column('binary_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('powers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('algonquian_title', sa.Integer(), nullable=False),
    sa.Column('binary_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('shapes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_name', sa.String(), nullable=False),
    sa.Column('delivery_type', sa.String(), nullable=True),
    sa.Column('binary_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('binary_code', sa.String(), nullable=False),
    sa.Column('binary_code_connected', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('techniques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('binary_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('spells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('power_id', sa.UUID(), nullable=False),
    sa.Column('shape_id', sa.UUID(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ),
    sa.ForeignKeyConstraint(['power_id'], ['powers.id'], ),
    sa.ForeignKeyConstraint(['shape_id'], ['shapes.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['targets.id'], ),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('sub_techniques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('technique_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('binary_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['technique_id'], ['techniques.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_techniques')
    op.drop_table('spells')
    op.drop_table('techniques')
    op.drop_table('targets')
    op.drop_table('shapes')
    op.drop_table('powers')
    op.drop_table('forms')
    # ### end Alembic commands ###
